baseURL = "https://joyce.fyi"
disablePathToLower = true
languageCode = "en-us"
title = "Joyce Kung"
theme = "cactus"
show_updated = false

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Literary Publications"
url = "/writings"
weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
    colortheme = "light"
    rss = true

    # Main page settings
    description = "I'm currently a <a href='https://polywork.com/joyce'>site reliability engineer</a> in Tkarón:to (Toronto). I believe in good writing (docs, code, and words), empathy in tech, and the power of kind mentorship."
    mainSection = "posts"
    postsOnHomePage = 4
    tagsOverview = false
    projectsUrl = "writings"
    images = ['/img/twitter_card.png']

    [[params.social]]
    name = "twitter"
    link = "https://twitter.com/commitsbyjoyce"

    [[params.social]]
    name = "github"
    link = "https://github.com/thejoycekung"

    [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/thejoycekung"
