[build.environment]
  HUGO_VERSION = "0.74.3"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"
  publish = "public/"

[[redirects]]
  from = "https://joycekung.netlify.app"
  to = "https://joyce.fyi"
  status = 301
  force = true
