name: Deploy to GH Pages
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Hugo to GH Pages
      uses: chabad360/hugo-gh-pages@v1.2
      with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
          branch: publish
          
